version: "3"

services:
  guestbook-golang:
    image: "guestbook-golang"
    container_name: "guestbook-golang"
    environment:
      - "SYSTEM_ENV=local"
      - "SYSTEM_REDIS_HOST=guestbook-redis"
      - "SYSTEM_REDIS_PORT=6379"
    volumes:
      - "./api:/go/src/github.com/becosuke/guestbook-api:cached"
    tty: "yes"

  guestbook-node:
    image: "node:13-alpine"
    container_name: "guestbook-node"
    environment:
      - "SYSTEM_ENV=local"
      - "NUXT_HOST=0.0.0.0"
      - "NUXT_PORT=3000"
    volumes:
      - "./nuxt:/opt/guestbook-nuxt"
    ports:
      - "3000:3000"
    tty: "yes"

  guestbook-redis:
    image: "redis:alpine"
    container_name: "guestbook-redis"
    volumes:
      - "./redis/data:/data:delegated"

  guestbook-api:
    image: "guestbook-api"
    container_name: "guestbook-api"
    environment:
      - "SYSTEM_ENV=local"
      - "SYSTEM_REDIS_HOST=guestbook-redis"
      - "SYSTEM_REDIS_PORT=6379"
    ports:
      - "8080:80"
