version: "3"

services:
  guestbook-golang:
    image: "guestbook-golang"
    container_name: "guestbook-golang"
    environment:
      - "SYSTEM_ENV=local"
      - "SYSTEM_REDIS_HOST=guestbook-redis"
      - "SYSTEM_REDIS_PORT=6379"
    volumes:
      - "./guestbook-api:/go/src/github.com/becosuke/guestbook-api:cached"
    working_dir: "/go/src/github.com/becosuke/guestbook-api"
    tty: "yes"

  guestbook-node:
    image: "node:13-alpine"
    container_name: "guestbook-node"
    environment:
      - "SYSTEM_ENV=local"
      - "NUXT_HOST=0.0.0.0"
      - "NUXT_PORT=3000"
    volumes:
      - "./guestbook-nuxt:/opt/guestbook-nuxt:cached"
    working_dir: "/opt/guestbook-nuxt"
    tty: "yes"

  guestbook-nginx:
    image: "nginx:alpine"
    container_name: "guestbook-nginx"
    volumes:
      - "./nginx/files/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro"
    ports:
      - "3000:3000"
      - "80:80"
      - "8000:8000"

  guestbook-redis:
    image: "redis:alpine"
    container_name: "guestbook-redis"
    volumes:
      - "./redis/data:/data:delegated"

  guestbook-api:
    image: "guestbook-api"
    container_name: "guestbook-api"
    environment:
      - "SYSTEM_ENV=local"
      - "SYSTEM_REDIS_HOST=guestbook-redis"
      - "SYSTEM_REDIS_PORT=6379"
